### ISSUE TITLE
Immer noch Workaround-URL für INTERLIS-Repo?

### ISSUE THREAD

**Issue by schmandr** [sogis/ilivalidator-web-service#16]
Jetzt habe ich hier doch nochmal eine Frage: Steht in der folgenden Zeile nicht doch immer noch die Workaround-URL für das INTERLIS-Repo? Die sollte es nun doch nicht mehr brauchen.

https://github.com/sogis/ilivalidator-web-service/blob/4a10f3798ab3ecc3bf80cab208cbb043290dc235/src/main/java/ch/so/agi/ilivalidator/services/IlivalidatorService.java#L68

**Comment by edigonzales** [comment]
fixed https://github.com/sogis/ilivalidator-web-service/commit/904b6529187d57210ebb55752d613ee09a056ca1
